-- ACP Health — Database Schema (PostgreSQL)
-- ============================================================
-- Design intent: every triage decision is logged with enough
-- context that a licensed clinician can later review it and
-- mark it correct/incorrect. "Improving AI performance" here
-- means growing this clinician-reviewed dataset over time —
-- NOT auto-retraining a model on raw user conversations without
-- review. Do not remove the clinician_reviews loop.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------- Users ----------
CREATE TABLE users (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email           TEXT UNIQUE,                -- nullable: pilot users may be pseudonymous
  role            TEXT NOT NULL DEFAULT 'pilot_user'
                    CHECK (role IN ('pilot_user', 'clinician', 'admin')),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at      TIMESTAMPTZ                 -- soft delete, for data-deletion requests
);

-- ---------- Invite codes (real server-side gating, not client-side) ----------
CREATE TABLE invite_codes (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code_hash       TEXT NOT NULL UNIQUE,        -- store a hash, never the raw code
  label           TEXT,                        -- e.g. "clinician-batch-1"
  max_uses        INTEGER NOT NULL DEFAULT 1,
  uses            INTEGER NOT NULL DEFAULT 0,
  expires_at      TIMESTAMPTZ,
  active          BOOLEAN NOT NULL DEFAULT true,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- Consent record (required before any conversation starts) ----------
CREATE TABLE consents (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID NOT NULL REFERENCES users(id),
  terms_version   TEXT NOT NULL,               -- ties to a specific reviewed T&C/disclaimer version
  agreed_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- Conversations ----------
CREATE TABLE conversations (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID NOT NULL REFERENCES users(id),
  started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at        TIMESTAMPTZ,
  status          TEXT NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active', 'completed', 'abandoned'))
);

CREATE TABLE messages (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL REFERENCES conversations(id),
  sender          TEXT NOT NULL CHECK (sender IN ('user', 'bot')),
  content         TEXT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- Triage results (produced by the RULE ENGINE, not free-form LLM output) ----------
CREATE TABLE triage_results (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL REFERENCES conversations(id),
  tier            TEXT NOT NULL CHECK (tier IN ('emergency', 'urgent', 'self_care')),
  rule_version    TEXT NOT NULL,               -- e.g. "v1-draft-2026-07-01" — track which rule set decided this
  raw_inputs      JSONB NOT NULL,               -- structured answers the rules engine used
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- Clinician review loop (THIS is how the system safely improves) ----------
CREATE TABLE clinician_reviews (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  triage_result_id  UUID NOT NULL REFERENCES triage_results(id),
  clinician_id      UUID NOT NULL REFERENCES users(id),   -- must have role='clinician'
  agreed_with_tier  BOOLEAN NOT NULL,
  corrected_tier    TEXT CHECK (corrected_tier IN ('emergency', 'urgent', 'self_care')),
  notes             TEXT,
  reviewed_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- Medicine reference lookups (doctor-gated, reference-only) ----------
CREATE TABLE medicine_lookups (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id   UUID NOT NULL REFERENCES conversations(id),
  drug_name         TEXT NOT NULL,
  doctor_confirmed  BOOLEAN NOT NULL DEFAULT false,  -- user attested a doctor prescribed this
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Curated reference table — NOT freely generated by the LLM.
-- Populate this from a licensed drug-information source, not model output.
CREATE TABLE medicine_reference (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  drug_name         TEXT NOT NULL UNIQUE,
  summary           TEXT NOT NULL,
  source            TEXT NOT NULL,              -- citation for where this info came from
  last_reviewed_at  TIMESTAMPTZ
);

-- ---------- Clinic cache (server-side; keeps the Places API key off the client) ----------
CREATE TABLE clinic_cache (
  place_id        TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  address         TEXT,
  lat             DOUBLE PRECISION,
  lng             DOUBLE PRECISION,
  rating          NUMERIC,
  raw_json        JSONB,
  fetched_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- User feedback ----------
CREATE TABLE feedback (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID REFERENCES conversations(id),
  user_id         UUID REFERENCES users(id),
  rating          INTEGER CHECK (rating BETWEEN 1 AND 5),
  comment         TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- Data deletion requests (privacy compliance) ----------
CREATE TABLE data_deletion_requests (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID NOT NULL REFERENCES users(id),
  requested_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  fulfilled_at    TIMESTAMPTZ
);

CREATE INDEX idx_messages_conversation ON messages(conversation_id);
CREATE INDEX idx_triage_conversation ON triage_results(conversation_id);
CREATE INDEX idx_reviews_triage ON clinician_reviews(triage_result_id);

-- ============================================================
-- Doctor consultation booking, payment, and video-call handoff
-- ============================================================
-- This is a real human doctor consultation, booked and paid for
-- through the platform. The AI never diagnoses or prescribes —
-- it only helps a patient reach a licensed doctor faster. Every
-- doctor here must be verified and licensed for the patient's
-- jurisdiction before being bookable.

CREATE TABLE doctors (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name                TEXT NOT NULL,
  email               TEXT NOT NULL UNIQUE,
  specialty           TEXT,
  license_number      TEXT NOT NULL,
  license_jurisdiction TEXT NOT NULL,          -- e.g. 'ON, Canada' — must match patient's location
  verified            BOOLEAN NOT NULL DEFAULT false,  -- true only after manual license verification
  fee_cents           INTEGER NOT NULL,        -- consultation fee, in the smallest currency unit
  currency             TEXT NOT NULL DEFAULT 'CAD',
  stripe_account_id   TEXT,                    -- Stripe Connect account (destination of payout)
  zoom_host_email     TEXT,                    -- doctor's Zoom account for meeting creation
  active              BOOLEAN NOT NULL DEFAULT true,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE appointments (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id     UUID NOT NULL REFERENCES conversations(id),
  patient_id          UUID NOT NULL REFERENCES users(id),
  doctor_id           UUID NOT NULL REFERENCES doctors(id),
  triage_result_id    UUID REFERENCES triage_results(id),   -- what prompted this booking
  status              TEXT NOT NULL DEFAULT 'requested'
                        CHECK (status IN ('requested','payment_pending','confirmed','completed','cancelled')),
  requested_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  scheduled_at        TIMESTAMPTZ,
  zoom_meeting_id     TEXT,
  zoom_join_url       TEXT,
  zoom_host_url       TEXT,
  visit_summary_url   TEXT                    -- link to the auto-generated visit-prep doc, sent to the doctor
);

CREATE TABLE payments (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  appointment_id        UUID NOT NULL REFERENCES appointments(id),
  amount_cents          INTEGER NOT NULL,       -- total charged to patient
  platform_fee_cents    INTEGER NOT NULL,       -- the platform's cut (5-10%)
  doctor_payout_cents   INTEGER NOT NULL,       -- amount_cents - platform_fee_cents
  currency              TEXT NOT NULL DEFAULT 'CAD',
  stripe_payment_intent_id TEXT,
  status                TEXT NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending','succeeded','failed','refunded')),
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_appointments_patient ON appointments(patient_id);
CREATE INDEX idx_appointments_doctor ON appointments(doctor_id);
CREATE INDEX idx_payments_appointment ON payments(appointment_id);

